// Code generated by scripts/regen-embedded.sh and scripts/build-singbox.sh; DO NOT EDIT.
package installer

const RequiredVersion = "1.14.0-alpha.29"

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.29/sing-box-1.14.0-alpha.29-mipsel-3.4", SHA256: "195b2a80c0418f2049e7cc6d0ea8c1499a62efbe2b5bbb93b5b2161071a1c25d", Size: 86342340},
	"mips-3.4":     {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.29/sing-box-1.14.0-alpha.29-mips-3.4", SHA256: "11f6ab56801f8cf83fc322811ef66e81b73dbdd42d75651558c8be699d3a5b53", Size: 69075123},
	"aarch64-3.10": {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.29/sing-box-1.14.0-alpha.29-aarch64-3.10", SHA256: "355078fcfac94b7e03b5cb72649b4f5ba006256c873d114e6a9806d54751aa20", Size: 72329176},
}
