// Code generated by scripts/regen-embedded.sh and scripts/build-singbox.sh; DO NOT EDIT.
package installer

const RequiredVersion = "1.14.0-alpha.34"

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.34/sing-box-1.14.0-alpha.34-mipsel-3.4", SHA256: "58f118d99a8195da3f9c5fec26fb2c2fb3d8044cfa550eefa54038c183032eb9", Size: 89781364},
	"mips-3.4":     {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.34/sing-box-1.14.0-alpha.34-mips-3.4", SHA256: "d4323020deb09a79290cb1080621dfbe4bd38431b840020dcb6f1149e89dc149", Size: 72548509},
	"aarch64-3.10": {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/develop/singbox/1.14.0-alpha.34/sing-box-1.14.0-alpha.34-aarch64-3.10", SHA256: "eabfd5b052d9778e23bdff81f02ed5df29e73c9e6a3dbc3917db63d1836192f4", Size: 75298328},
}
